// Scans public/certificates for image+pdf pairs and updates
// data/certificates.meta.json + src/data/certificates.ts (preserving rank/meta).
// Usage: npm run sync:certs
import { readdirSync, existsSync, readFileSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const pubDir = join(root, "public", "certificates");
const metaPath = join(root, "data", "certificates.meta.json");
const outPath = join(root, "src", "data", "certificates.ts");

const IMG = new Set([".jpg", ".jpeg", ".png", ".webp"]);
const DOC = new Set([".pdf", ".jpg", ".jpeg", ".png"]);

let meta = {};
if (existsSync(metaPath)) meta = JSON.parse(readFileSync(metaPath, "utf8"));

if (!existsSync(pubDir)) {
  console.log("No public/certificates yet — copy them from the main portfolio first.");
  process.exit(0);
}

const files = readdirSync(pubDir);
const stems = new Map();
for (const f of files) {
  const dot = f.lastIndexOf(".");
  if (dot < 0) continue;
  const stem = f.slice(0, dot);
  const ext = f.slice(dot).toLowerCase();
  const e = stems.get(stem) ?? {};
  if (IMG.has(ext) && !e.image) e.image = f;
  if (DOC.has(ext) && !e.doc) e.doc = f;
  stems.set(stem, e);
}

const rows = [];
let rank = 1;
for (const [stem, e] of [...stems.entries()].sort()) {
  if (!e.image) continue;
  const m = meta[stem] ?? {};
  const id = m.id ?? String(rank);
  rows.push({
    id,
    rank: m.rank ?? 90 + rank,
    title: m.title ?? stem.replace(/[_-]+/g, " "),
    imageUrl: `/certificates/${e.image}`,
    downloadUrl: `/certificates/${e.doc ?? e.image}`,
    category: m.category ?? "Uncategorized",
    issuer: m.issuer ?? "",
    year: m.year ?? "",
  });
  meta[stem] = { id, rank: m.rank ?? 90 + rank, title: rows[rows.length - 1].title, category: rows[rows.length - 1].category, issuer: m.issuer ?? "", year: m.year ?? "" };
  rank++;
}

rows.sort((a, b) => a.rank - b.rank);
writeFileSync(metaPath, JSON.stringify(meta, null, 2));
writeFileSync(
  outPath,
  `import type { Certificate } from "@/types";\n\n// AUTO-GENERATED by npm run sync:certs — edit rank/meta in data/certificates.meta.json\n// Ranked: rank 1 = most valuable, homepage shows rank 1–3.\nexport const certificates: Certificate[] = ${JSON.stringify(rows, null, 2)};\n`
);
console.log(`Synced ${rows.length} certificates → src/data/certificates.ts`);
